// File: utils/stockList.js

// Include your existing top200 array here
export const stockList = [

  { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', exchange: 'NASDAQ' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', exchange: 'NASDAQ' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ' },
  { symbol: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ' },
  { symbol: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', exchange: 'NASDAQ' },
  { symbol: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ' },
  { symbol: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ' },
  { symbol: 'ORCL', name: 'Oracle Corp.', exchange: 'NYSE' },
  { symbol: 'INTC', name: 'Intel Corp.', exchange: 'NASDAQ' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ' },
  { symbol: 'CRM', name: 'Salesforce, Inc.', exchange: 'NYSE' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', exchange: 'NASDAQ' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', exchange: 'NASDAQ' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', exchange: 'NASDAQ' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.', exchange: 'NASDAQ' },
  { symbol: 'KO', name: 'The Coca-Cola Co.', exchange: 'NYSE' },
  { symbol: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.', exchange: 'NASDAQ' },
  { symbol: 'HD', name: 'The Home Depot, Inc.', exchange: 'NYSE' },
  { symbol: 'LOW', name: 'Lowe’s Companies, Inc.', exchange: 'NYSE' },
  { symbol: 'TGT', name: 'Target Corp.', exchange: 'NYSE' },
  { symbol: 'MCD', name: 'McDonald’s Corp.', exchange: 'NYSE' },
  { symbol: 'SBUX', name: 'Starbucks Corp.', exchange: 'NASDAQ' },
  { symbol: 'NKE', name: 'NIKE, Inc.', exchange: 'NYSE' },
  { symbol: 'DIS', name: 'The Walt Disney Co.', exchange: 'NYSE' },
  { symbol: 'T', name: 'AT&T Inc.', exchange: 'NYSE' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.', exchange: 'NYSE' },
  { symbol: 'XOM', name: 'Exxon Mobil Corp.', exchange: 'NYSE' },
  { symbol: 'CVX', name: 'Chevron Corp.', exchange: 'NYSE' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE' },
  { symbol: 'BAC', name: 'Bank of America Corp.', exchange: 'NYSE' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.', exchange: 'NYSE' },
  { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE' },
  { symbol: 'MA', name: 'Mastercard Inc.', exchange: 'NYSE' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', exchange: 'NYSE' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE' },
  { symbol: 'LLY', name: 'Eli Lilly and Co.', exchange: 'NYSE' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.', exchange: 'NYSE' },
  { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', exchange: 'NYSE' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE' },
  { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Co.', exchange: 'NYSE' },
  { symbol: 'GILD', name: 'Gilead Sciences, Inc.', exchange: 'NASDAQ' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals, Inc.', exchange: 'NASDAQ' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { symbol: 'ISRG', name: 'Intuitive Surgical, Inc.', exchange: 'NASDAQ' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE' },
  { symbol: 'MDT', name: 'Medtronic plc', exchange: 'NYSE' },
  { symbol: 'SYK', name: 'Stryker Corp.', exchange: 'NYSE' },
  { symbol: 'CI', name: 'The Cigna Group', exchange: 'NYSE' },
  { symbol: 'ELV', name: 'Elevance Health Inc.', exchange: 'NYSE' },
  { symbol: 'BDX', name: 'Becton, Dickinson and Co.', exchange: 'NYSE' },
  { symbol: 'ADP', name: 'Automatic Data Processing, Inc.', exchange: 'NASDAQ' },
  { symbol: 'INTU', name: 'Intuit Inc.', exchange: 'NASDAQ' },
  { symbol: 'NOW', name: 'ServiceNow, Inc.', exchange: 'NYSE' },
  { symbol: 'PANW', name: 'Palo Alto Networks, Inc.', exchange: 'NASDAQ' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', exchange: 'NYSE' },
  { symbol: 'ZS', name: 'Zscaler, Inc.', exchange: 'NASDAQ' },
  { symbol: 'DDOG', name: 'Datadog, Inc.', exchange: 'NASDAQ' },
  { symbol: 'MDB', name: 'MongoDB, Inc.', exchange: 'NASDAQ' },
  { symbol: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE' },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.', exchange: 'NYSE' },
  { symbol: 'LYFT', name: 'Lyft, Inc.', exchange: 'NASDAQ' },
  { symbol: 'ROKU', name: 'Roku, Inc.', exchange: 'NASDAQ' },
  { symbol: 'DOCU', name: 'DocuSign, Inc.', exchange: 'NASDAQ' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.', exchange: 'NYSE' },
  { symbol: 'ETSY', name: 'Etsy, Inc.', exchange: 'NASDAQ' },
  { symbol: 'U', name: 'Unity Software Inc.', exchange: 'NYSE' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'SQ', name: 'Block, Inc.', exchange: 'NYSE' },
  { symbol: 'F', name: 'Ford Motor Co.', exchange: 'NYSE' },
  { symbol: 'GM', name: 'General Motors Co.', exchange: 'NYSE' },
  { symbol: 'AIG', name: 'American International Group, Inc.', exchange: 'NYSE' },
  { symbol: 'ALL', name: 'The Allstate Corp.', exchange: 'NYSE' },
  { symbol: 'AFL', name: 'Aflac Inc.', exchange: 'NYSE' },
  { symbol: 'BK', name: 'The Bank of New York Mellon Corp.', exchange: 'NYSE' },
  { symbol: 'BLK', name: 'BlackRock, Inc.', exchange: 'NYSE' },
  { symbol: 'CB', name: 'Chubb Limited', exchange: 'NYSE' },
  { symbol: 'CME', name: 'CME Group Inc.', exchange: 'NASDAQ' },
  { symbol: 'COF', name: 'Capital One Financial Corp.', exchange: 'NYSE' },
  { symbol: 'DFS', name: 'Discover Financial Services', exchange: 'NYSE' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', exchange: 'NASDAQ' },
  { symbol: 'GL', name: 'Globe Life Inc.', exchange: 'NYSE' },
  { symbol: 'HIG', name: 'The Hartford Financial Services Group, Inc.', exchange: 'NYSE' },
  { symbol: 'ICE', name: 'Intercontinental Exchange, Inc.', exchange: 'NYSE' },
  { symbol: 'KEY', name: 'KeyCorp', exchange: 'NYSE' },
  { symbol: 'MET', name: 'MetLife, Inc.', exchange: 'NYSE' },
  { symbol: 'MKTX', name: 'MarketAxess Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'MTB', name: 'M&T Bank Corp.', exchange: 'NYSE' },
  { symbol: 'NTRS', name: 'Northern Trust Corp.', exchange: 'NASDAQ' },
  { symbol: 'PFG', name: 'Principal Financial Group, Inc.', exchange: 'NASDAQ' },
  { symbol: 'PRU', name: 'Prudential Financial, Inc.', exchange: 'NYSE' },
  { symbol: 'RE', name: 'Everest Re Group, Ltd.', exchange: 'NYSE' },
  { symbol: 'RF', name: 'Regions Financial Corp.', exchange: 'NYSE' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corp.', exchange: 'NYSE' },
  { symbol: 'SIVB', name: 'SVB Financial Group', exchange: 'NASDAQ' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE' },
  { symbol: 'STT', name: 'State Street Corp.', exchange: 'NYSE' },
  { symbol: 'SYF', name: 'Synchrony Financial', exchange: 'NYSE' },
  { symbol: 'TRV', name: 'The Travelers Companies, Inc.', exchange: 'NYSE' },
  { symbol: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.', exchange: 'NYSE' },
  { symbol: 'ZION', name: 'Zions Bancorporation', exchange: 'NASDAQ' },
  { symbol: 'BA', name: 'The Boeing Co.', exchange: 'NYSE' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE' },
  { symbol: 'CMI', name: 'Cummins Inc.', exchange: 'NYSE' },
  { symbol: 'DE', name: 'Deere & Co.', exchange: 'NYSE' },
  { symbol: 'DHR', name: 'Danaher Corp.', exchange: 'NYSE' },
  { symbol: 'DOV', name: 'Dover Corp.', exchange: 'NYSE' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', exchange: 'NYSE' },
  { symbol: 'ETN', name: 'Eaton Corp. plc', exchange: 'NYSE' },
  { symbol: 'FAST', name: 'Fastenal Co.', exchange: 'NASDAQ' },
  { symbol: 'FDX', name: 'FedEx Corp.', exchange: 'NYSE' },
  { symbol: 'GE', name: 'General Electric Co.', exchange: 'NYSE' },
  { symbol: 'HON', name: 'Honeywell International Inc.', exchange: 'NASDAQ' },
  { symbol: 'IBM', name: 'International Business Machines Corp.', exchange: 'NYSE' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.', exchange: 'NYSE' },
  { symbol: 'JCI', name: 'Johnson Controls International plc', exchange: 'NYSE' },
  { symbol: 'LMT', name: 'Lockheed Martin Corp.', exchange: 'NYSE' },
  { symbol: 'MMM', name: '3M Co.', exchange: 'NYSE' },
  { symbol: 'NOC', name: 'Northrop Grumman Corp.', exchange: 'NYSE' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', exchange: 'NASDAQ' },
  { symbol: 'PNR', name: 'Pentair plc', exchange: 'NYSE' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.', exchange: 'NYSE' },
  { symbol: 'ROP', name: 'Roper Technologies, Inc.', exchange: 'NASDAQ' },
  { symbol: 'RTX', name: 'RTX Corp.', exchange: 'NYSE' },
  { symbol: 'SNA', name: 'Snap-on Inc.', exchange: 'NYSE' },
  { symbol: 'SWK', name: 'Stanley Black & Decker Inc.', exchange: 'NYSE' },
  { symbol: 'TXT', name: 'Textron Inc.', exchange: 'NYSE' },
  { symbol: 'UNP', name: 'Union Pacific Corp.', exchange: 'NYSE' },
  { symbol: 'XYL', name: 'Xylem Inc.', exchange: 'NYSE' }
];


console.log("✅ stockList loaded:", stockList.length);

// מחזיר סימבול בפורמט של TradingView (למשל "NASDAQ:AAPL")
export function getTradingViewSymbol(symbol) {
  const stock = stockList.find(s => s.symbol === symbol);
  if (!stock) return `NASDAQ:${symbol}`; // fallback
  return `${stock.exchange}:${stock.symbol}`;
}

// מחזיר רק את שם הבורסה (למשל "NASDAQ")
export function getExchangePrefix(symbol) {
  const stock = stockList.find(s => s.symbol === symbol);
  if (!stock) return 'NASDAQ';
  return stock.exchange;
}
